name: SQS proxy rabbitmq

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: us-east-1

jobs:
  infra-up:
    name: Infra up to aws
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.5
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Create terraform.tfvars file
        working-directory: "./aws-infra"
        run: |
          cat >terraform.tfvars<<EOL
          preFixName="matheusrosmano-sqs-proxy-rabbitmq"
          EOL

      - name: Create the file main.tf
        working-directory: "./aws-infra"
        run: |
          mv main.tf.modelo main.tf
          sed -i "s|<ORGANIZATION_NAME>|${{ secrets.ORGANIZATION_NAME }}|g" main.tf
          sed -i "s|<WORKSPACE_NAME>|${{ secrets.WORKSPACE_NAME }}|g" main.tf
          sed -i "s|<BUCKET_RESOURCES_REGION>|${{ env.AWS_REGION }}|g" main.tf
          sed -i "s|<AWS_ACCESS_KEY_ID>|${{ secrets.AWS_ACCESS_KEY_ID }}|g" main.tf
          sed -i "s|<AWS_SECRET_ACCESS_KEY>|${{ secrets.AWS_SECRET_ACCESS_KEY }}|g" main.tf

      - name: Terraform init
        working-directory: "./aws-infra"
        run: terraform init

      - name: Terraform validate
        working-directory: "./aws-infra"
        run: terraform validate

      - name: Terraform apply
        working-directory: "./aws-infra"
        run: terraform apply -auto-approve

      # - name: Setup Go environment
      #   uses: actions/setup-go@v3.3.1
      #   with:
      #     go-version: "1.19"
      #     cache: true

      # - name: Go mod tidy
      #   run: go mod tidy

      # - name: Setup AWS SAM CLI
      #   uses: aws-actions/setup-sam@v2

      # - name: SAM BUILD
      #   run: sam build

      # - name: SAM validate
      #   run: sam validate

      # - name: Sam deploy
      #   run: |
      #     sam deploy --stack-name sqs-proxy-rabbitmq \
      #     --s3-bucket matheusrosmano-lambdas-state \
      #     --parameter-overrides \
      #         environment=development \
      #     --capabilities CAPABILITY_IAM \
      #     --no-confirm-changeset
